// <auto-generated />
using EntityFrameWorkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EntityFrameWorkCore.Migrations
{
    [DbContext(typeof(ServerManageDbContext))]
    [Migration("20180120022500_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entitys.ServerList", b =>
                {
                    b.Property<string>("ServerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ServerAuthority");

                    b.Property<string>("ServerName");

                    b.Property<string>("ServerPass");

                    b.HasKey("ServerId");

                    b.ToTable("ServerList");
                });

            modelBuilder.Entity("Domain.Entitys.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserAuthority");

                    b.Property<string>("UserName");

                    b.Property<string>("UserPass");

                    b.HasKey("UserId");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
